### ISSUE TITLE
docs.rs build failed

### ISSUE THREAD

**Issue by vn-ki** [lpc55/lpc55-hal#41]
Docs are not visible for the crate. https://docs.rs/crate/lpc55-hal/0.0.3/builds

**Comment by nickray** [comment]
I'll try and make sure the next release (there are some open PRs) will render. It seems the issue is that thumbv8m is not installed on the docs.rs build server, but it should be possible to just build docs on x86_64.

**Comment by nickray** [comment]
Tada: https://docs.rs/lpc55-hal/0.0.4/lpc55_hal/
